name: Action for Deploy

on:
  push:
    branches:
      - 'main'

jobs:

  artifact:

    name: Test master branch - GitHub Packages
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Copy repository contents via scp
       uses: appleboy/scp-action@master
       env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
       with:
        source: "."
        target: "/var/www/mywebsite" #location that want to use as temporary folder to build project
     - name: Build Project & Move Project to Tomcat Folder
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.HOST }}
         USERNAME: ${{ secrets.USERNAME }}
         PORT: ${{ secrets.PORT }}
         KEY: ${{ secrets.SSHKEY }}
         script: |
            pwd #probably we are in wrong directory here
            mvn -B clean package -DskipTests
            pwd
            cd ~ #temporary folder 
            mv . . #move content (war file) from temporary folder to tomcat location
